// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUwqer2Qqdr-KrNUD6L4V39rPhzG-7GsI',
    appId: '1:953113321611:android:29f4505f50027448ce748e',
    messagingSenderId: '953113321611',
    projectId: 'brightbuds-15065',
    storageBucket: 'brightbuds-15065.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsibis7hsVI_sVPzivwRimTT2-ziPrjgk',
    appId: '1:953113321611:ios:4bf3654136d975e0ce748e',
    messagingSenderId: '953113321611',
    projectId: 'brightbuds-15065',
    storageBucket: 'brightbuds-15065.firebasestorage.app',
    iosBundleId: 'com.example.brightbudsNew',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARR59BlH2uNllBtL-rjW3xAalkGfHa2NU',
    appId: '1:953113321611:web:f281cdf043d866e4ce748e',
    messagingSenderId: '953113321611',
    projectId: 'brightbuds-15065',
    authDomain: 'brightbuds-15065.firebaseapp.com',
    storageBucket: 'brightbuds-15065.firebasestorage.app',
  );

}